# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gii_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from typing import List
from add_cmd import Ui_SecondWindow
import git 
server_1 = git.RemoteCon()
global flag
import json

f = open("config.json")
configs = json.load(f)


class Ui_MainWindow(object):
    flag=1
    cred_index = ""
    def __init__(self):
        self.flag=0
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(492, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(99, 9, 171, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.serverList = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.serverList.setObjectName("serverList")
        self.serverList.addItems(self.dropDown()) #calling dropDown method
        
        self.verticalLayout.addWidget(self.serverList)
        self.textEdit = QtWidgets.QTextBrowser(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 180, 471, 271))
        self.textEdit.setObjectName("textEdit")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(100, 130, 171, 23))
        self.runButton.setObjectName("runButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 61, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 61, 16))
        self.label_3.setObjectName("label_3")
        
        self.con_status = QtWidgets.QLabel(self.centralwidget)
        self.con_status.setGeometry(QtCore.QRect(10, 460, 141, 16))
        self.con_status.setObjectName("con_status")
        
        self.con_label = QtWidgets.QLabel(self.centralwidget)
        self.con_label.setGeometry(QtCore.QRect(120, 460, 81, 16))
        self.con_label.setObjectName("con_label")
        self.con_label.setText("Disconnected")
        self.con_label.setStyleSheet("color: red;")
        
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(100, 70, 171, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.commandList = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.commandList.setObjectName("commandList")
        self.verticalLayout_2.addWidget(self.commandList)
        self.addCommandBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addCommandBtn.setGeometry(QtCore.QRect(300, 90, 101, 23))
        self.addCommandBtn.setObjectName("addCommandBtn")
        self.addCommandBtn.clicked.connect(self.newWindow)
        
        self.check_con = QtWidgets.QPushButton(self.centralwidget)
        self.check_con.setGeometry(QtCore.QRect(300, 30, 101, 23))
        self.check_con.setObjectName("check_con")
        self.check_con.clicked.connect(self.connect)
        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 492, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.runButton.clicked.connect(self.b1_clicked)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Git System Management"))
        MainWindow.setWindowFlags(MainWindow.windowFlags() & ~QtCore.Qt.WindowMaximizeButtonHint)
    
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.label.setText(_translate("MainWindow", "Server:"))
        self.label_3.setText(_translate("MainWindow", "Command:"))
        self.con_status.setText(_translate("MainWindow", "Connection Status:"))
        self.addCommandBtn.setText(_translate("MainWindow", "Add Command"))
        self.check_con.setText(_translate("MainWindow", "Check Connection"))
    def b1_clicked(self): # when RUN button is clicked
        res = self.showResut()
        self.textEdit.setPlainText(res)
    def dropDown(self): #ip lists for drow down
        url = []
        for index,item in configs.items():
            url.append(index) 
        return url
    def dropDownCommand(self):#ip lists for drow down
        url = []
        for index,item in configs[self.cred_index]['commands'].items():
            url.append(index) 
        self.commandList.clear()
        self.commandList.addItems(url)
    def listToString(self,s): 
        # initialize an empty string
        str1 = ""       
        # traverse in the string  
        for ele in s: 
            str1 += str(ele)
        # return string  
        return str1
    def showResut(self): #command execution
        selected = self.commandList.currentText()
        command = configs[self.cred_index]['commands'][selected]
        s = server_1.execute_commands(command)
        return self.listToString(s)
      
    
    def connect(self):
        # if (self.flag == 0):
        if not server_1.check_connection_status():
            self.cred_index = str(self.serverList.currentText())
            creds = configs[self.cred_index]['creds']
            server_1.connect(creds)
            self.dropDownCommand()
            self.con_label.setText("Connected")
            self.con_label.setStyleSheet("color: Green;")
        else:
            server_1.disconnect()
            self.con_label.setText("Disonnected")
            self.con_label.setStyleSheet("color: red;")
            self.connect()
    def newWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SecondWindow()
        self.ui.setupUi(self.window, self.cred_index)
        self.window.show()
        
    
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
